### ISSUE TITLE
IDEA: Change the color of the tab

### ISSUE THREAD

**Issue by custa1200** [Khan/tota11y#99]
I'd like to be able to set the color for the tab to match the Styleguide branding colors I am working in. Would it be best to just use a CSS override or is this something that should be some piece of config for the JS?

**Comment by jdan** [comment]
Hey @custa1200,

Currently a hacky CSS override is the only way to accomplish this: http://jsbin.com/xubuwu/edit?html,css,output

```css
#tota11y-toolbar {
  background-color: green !important;
}

button.tota11y-toolbar-toggle {
  background-color: purple !important;
}

div.tota11y-info {
  background-color: red !important;
}
```

Does that answer your question?
